### ISSUE TITLE
NAs in "seat_incumbency_end_date"

### ISSUE THREAD

**Issue by jblumenau** [olihawkins/pdpr#1]
Hi Oli,

I came across a strange thing this morning:

    library(pdpr)
    commons_memberships <- fetch_commons_memberships()
    table(is.na(commons_memberships$seat_incumbency_end_date))
    > TRUE 
    > 9072 

It's odd because this wasn't happening at all when I've used that function over the past few days. 

Anyhow, thought you might like to know! Great package, by the way.

Jack

**Comment by olihawkins** [comment]
Hi Jack,

Good to hear from you. Are you still getting the same thing? I just tried it now and got a different result.

```r
library(pdpr)
commons_memberships <- fetch_commons_memberships()
table(is.na(commons_memberships$seat_incumbency_end_date))

FALSE  TRUE 
 8423   649 
```

Sounds like it could be (or could have been) an issue with a data platform update. I can ask the data platform developers if you're still getting the same problem.

**Comment by jblumenau** [comment]
Thanks for looking into it!

Huh, strange, yes I am still getting the same thing. It's weird because the rest of the data is being returned. It's only that one column that is NA.

If you wanted to pass the message on, I'd be happy to provide other details where necessary.

Thanks again.

**Comment by jblumenau** [comment]
For what it is worth, I've mapped the `mnis_id`s from here to the theyworkforyou ids [at this gist](https://gist.github.com/jblumenau/95069b66b309aa96dd2a9d585d1d763e). In case it is useful!

**Comment by olihawkins** [comment]
Sure. Could you do me a quick favour first? Could you try installing the latest version of pdpr from GitHub using devtools and see if the behaviour changes. I don't remember seeing this before and I can't see anything explicitly related to it in the commit history, but I just want to be sure it's not my fault before asking the data platform team to investigate. So to be clear, you don't have any seat incumbency end dates at all?

This mnis_id to twfy_id lookup table looks amazing: really helpful!

**Comment by jblumenau** [comment]
Sorry, got distracted today.

Yup, just reinstalled and no luck. It's very strange as I've been using that function to call from the data platform pretty regularly over the past couple of days and had no problem, and then this morning that single variable became NA for some reason.

**Comment by olihawkins** [comment]
Okay. Well thanks for trying it. That's so weird, and frustrating not to be able to replicate it. It's like some sort of bad result has been cached in between you and the data somewhere. I will drop the data platform developers an email. Do you want me to email you the full commons memberships table in the meantime?

**Comment by jblumenau** [comment]
Thanks Oli, really appreciate it. No worries on the data, I managed to retrieve an old copy via Dropbox. Let me know if you need anything else from me!

**Comment by matthieubosquet** [comment]
Dear Jack,

I have never used Oli's library. My best guess is that the limits in place on our open SPARQL endpoint might not accomodate your workload. Specifically, the timeout in place on the https://api.parliament.uk/sparql endpoint might kick in before all triples are returned and let you see only part of the results.

If you can see the SPARQL generated, you could try running the SPARQL query in the UI which is paginated: https://api.parliament.uk/sparql

To fix the issue, you could try running your query against a local version of our knowledge graph.

Our knowledge graph can be run locally in a docker container. I have an image that gets updated daily with our latest data. See: https://hub.docker.com/r/ukparliament/graphdb

You can run it from the command line:

`docker run --rm -d -p 7200:7200 ukparliament/graphdb:latest`

Alternatively, you could download GraphDB free and restore the repository with our latest data dump:
- GraphDB free edition: https://www.ontotext.com/free-graphdb-download/
- Data download: https://api.parliament.uk/download

To modify the configuration of Oli's package, it is as far as I can tell only 2 files to modify. See: https://github.com/olihawkins/pdpr/issues/2

I hope this helps.

Matthieu

**Comment by olihawkins** [comment]
Hi Matthieu. Thank you very much for looking into this. I have some ideas for how I can make it possible to use the package with a different endpoint for the API.

**Comment by olihawkins** [comment]
Quick update on this: I have this working in the development version of the R package and am able to query a locally running version of the parliament repository in GraphDB via `http://localhost:7200/repositories/parliament`. I now need to implement the equivalent functionality for the Python version before I can update both packages, but I wanted to let you know progress is being made.

**Comment by olihawkins** [comment]
[Done](https://github.com/olihawkins/pdpr#settings)!
