### ISSUE TITLE
Add a settings file to enable alternate endpoint configuration

### ISSUE THREAD

**Issue by matthieubosquet** [olihawkins/pdpr#2]
Users might want to run a local copy of UK Parliament's knowledge graph in order to:
- accomodate offline work
- run older versions of the graph
- bypass throttling limits of the open SPARQL endpoint
- bypass the query timeout limit for long running queries
- getting more processing power for faster execution

Currently, I see two files with "api.parliament.uk":
https://github.com/olihawkins/pdpr/search?q=api.parliament.uk&unscoped_q=api.parliament.uk 
- R/utils.R
- R/core.R

Would it be possible to have a settings file at the root of the project that would be easily editable?

**Comment by olihawkins** [comment]
Hi Matthieu. I think the best way of doing this in the context of packages for R and Python would be to implement package settings that a user can configure at runtime. So you could call something like `pdpr::set_api_url(my_local_url)` and have all subsequent function calls from the package work with that URL as the endpoint. I have done something like this before in both R and Python packages so I think I can implement this in a similar way in both languages. I will hopefully have some time to look at it later this week. I will post news of any updates in this thread.

**Comment by olihawkins** [comment]
Quick update on this: I have this working in the development version of the R package and am able to query a locally running version of the parliament repository in GraphDB via `http://localhost:7200/repositories/parliament`. I now need to implement the equivalent functionality for the Python version before I can update both packages, but I wanted to let you know progress is being made.

**Comment by olihawkins** [comment]
[Done](https://github.com/olihawkins/pdpr#settings)!
